name: goworkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO111MODULE: "on"
  working-directory: .

jobs:
  goworkflow:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.7

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

      - name: Install and run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8

      #  - name: Run golangci-lint
      #    run: make lint

      - name: Run tests
        run: make test